name: UI Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  ui-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

    #instal browser
      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1.7.3

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run UI tests
        run: ./gradlew clean test

      #Archive test result
      - name: Archive Test Result
        uses: actions/upload-artifact@v4.6.2
        if: always()
        with:
          name: Cucumber Report
          path: target

      #deploy to GitHub Pages
      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v4.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: target
      
